version: "3.9"

services:
  webapp:
    container_name: coffee-shop-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__ConnectionStrings__DefaultConnection=Host=db;Port=5432;Username=postgres;Password=strong-password;Database=coffeeshop;
      - JwtOptions__SecretKey=Qw8vTz2pLk9sXy4rBv6nJc1eZt7uGh5m
      - JwtOptions__ExpiresHours=24
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: coffee-shop-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=coffeeshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=strong-password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d coffeeshop"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: