version: "3.9"

services:
  webapp:
    container_name: coffee-shop-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  db:
    container_name: coffee-shop-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=coffeeshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=strong-password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: